spring.application.name=project-grupo-6
spring.mustache.suffix=.html
#logging.level.org.springframework.web=DEBUG
logging.level.com.samskivert.mustache=DEBUG
logging.level.org.springframework.web.servlet.view.MustacheView=DEBUG
#logging.level.org.springframework.security=DEBUG
##
# See all security decisions (Permitall, Deny, etc.)
logging.level.org.springframework.security=TRACE

# See why petitions fail in Web (Mapping, Resolvers)
logging.level.org.springframework.web=DEBUG

# See the parameters that are sent to the DB (for the email/username)
logging.level.org.hibernate.orm.queries=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# See how the session works(if creating a new or invalid one)
logging.level.org.springframework.security.web.authentication.session=DEBUG

# ===============================
# CONFIG MySQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/crossfire_db?serverTimezone=UTC
spring.datasource.username=user
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIG HIBERNATE (JPA)
# ===============================
# Spring Boot creates tables automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# ===============================
# key HTTPS (SSL)
# ===============================
server.port=8443
server.ssl.key-store=classpath:keystore.jks
server.ssl.key-store-password=password
server.ssl.key-store-type=JKS
server.ssl.key-alias=selfsigned

# H2 console settings
##################################################
# Habilitates web console
#spring.h2.console.enabled=true

# Defines entry route (you can put whichever you like)
#spring.h2.console.path=/h2-console

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-part-count=50

# This is vital: sets the name of the DB so it doesn't change each time
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

#spring.h2.console.settings.web-allow-others=true
##################################################

