spring.application.name=project-grupo-6
spring.mustache.suffix=.html
logging.level.org.springframework.web=DEBUG
logging.level.com.samskivert.mustache=DEBUG
logging.level.org.springframework.web.servlet.view.MustacheView=DEBUG

# Habilitates web console
spring.h2.console.enabled=true

# Defines entry route (you can put whichever you like)
spring.h2.console.path=/h2-console

# This is vital: sets the name of the DB so it doesn't change each time
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.settings.web-allow-others=true